from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routes import api
from app.core.config import settings

app = FastAPI(
    title="Genesis API",
    description="API generated by Genesis Engine",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_HOSTS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(api.router, prefix="/api/v1", tags=["API"])

@app.get("/")
def read_root():
    return {"message": "Genesis API is running", "status": "healthy"}

@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "Genesis API",
        "version": "1.0.0"
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)