name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Deploy
      run: |
        echo "Building app..."
        docker-compose build
        echo "Deployment would happen here"
        # Add your deployment logic here
