from fastapi import APIRouter, Depends, HTTPException, status
from typing import List, Dict, Any

router = APIRouter()

@router.get("/status")
async def get_api_status():
    """Get API status"""
    return {
        "status": "running",
        "service": "Genesis API",
        "version": "1.0.0"
    }

@router.get("/info")
async def get_api_info():
    """Get API information"""
    return {
        "name": "Genesis API",
        "description": "API generated by Genesis Engine",
        "version": "1.0.0",
        "features": ["REST API", "Documentation"]
    }
